# Generated by Django 4.2.7 on 2025-12-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена Credit'),
        ),
    ]
